# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_exact <- function(real_hist, l2, x, len, k, eps) {
    .Call(`_histogramr_cpp_exact`, real_hist, l2, x, len, k, eps)
}

cpp_greedy <- function(real_hist, l2, x, len, k, modulator, init, eps) {
    .Call(`_histogramr_cpp_greedy`, real_hist, l2, x, len, k, modulator, init, eps)
}

